# Generated by Django 3.1.6 on 2021-02-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_address', models.CharField(max_length=300)),
                ('staff_contactno', models.CharField(max_length=10)),
                ('staff_email', models.CharField(max_length=100)),
                ('staff_dob', models.DateField()),
                ('staff_doj', models.DateField()),
                ('staff_status', models.CharField(choices=[('T', 'T'), ('N', 'N')], max_length=1)),
                ('staff_adharno', models.IntegerField(max_length=12)),
                ('staff_active', models.IntegerField(choices=[(1, 'Active'), (0, 'In-Active')], max_length=1)),
                ('desig_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='staff.designation')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('leave_hfday', models.IntegerField(choices=[(0, 'Half day Leave'), (1, 'Full Day Leave')], max_length=1)),
                ('leave_reason', models.CharField(max_length=300)),
                ('leave_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], max_length=1)),
                ('leave_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='staff.leavetype')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='staff.staff')),
            ],
        ),
    ]
