# Generated by Django 3.1.7 on 2021-02-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_address', models.CharField(max_length=300)),
                ('staff_contactno', models.IntegerField(unique=True)),
                ('staff_email', models.EmailField(max_length=100)),
                ('staff_dob', models.DateField()),
                ('staff_doj', models.DateField()),
                ('staff_status', models.CharField(choices=[('T', 'Teaching Staff'), ('N', 'Non-Teaching Staff')], max_length=1, unique=True)),
                ('staff_adharno', models.IntegerField()),
                ('staff_active', models.IntegerField(choices=[(1, 'Active'), (0, 'In-Active')])),
                ('desig_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='staff.designation')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('leave_hfday', models.IntegerField(choices=[(0, 'Half day Leave'), (1, 'Full Day Leave')])),
                ('leave_reason', models.CharField(max_length=300)),
                ('leave_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')])),
                ('leave_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='staff.leavetype')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='staff.staff')),
            ],
        ),
    ]
