# Generated by Django 3.1.7 on 2021-02-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_status',
            field=models.CharField(choices=[('T', 'Teaching Staff'), ('N', 'Non-Teaching Staff')], max_length=1),
        ),
    ]
