# Generated by Django 3.1.6 on 2021-02-26 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_settings', '0001_initial'),
        ('staff', '0002_auto_20210226_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='staff.staff')),
            ],
        ),
    ]
