# Generated by Django 3.1.7 on 2021-02-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_teachersubjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_active',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'In-Active')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_adharno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_contactno',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_status',
            field=models.EmailField(choices=[('T', 'Teaching Staff'), ('N', 'Non-Teaching Staff')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='leave_hfday',
            field=models.IntegerField(choices=[(0, 'Half day Leave'), (1, 'Full Day Leave')]),
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='leave_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')]),
        ),
    ]
