# Generated by Django 3.1.6 on 2021-02-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_auto_20210226_1558'),
        ('user_settings', '0002_auto_20210226_1559'),
    ]

    operations = [
    ]
