# Generated by Django 3.1.6 on 2021-02-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_auto_20210226_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cast',
            new_name='Caste',
        ),
        migrations.RenameField(
            model_name='caste',
            old_name='cast_name',
            new_name='caste_name',
        ),
    ]
