# Generated by Django 3.1.7 on 2021-02-27 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_settings', '__first__'),
        ('academic_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_admno', models.CharField(max_length=15)),
                ('stud_regdate', models.DateField(default=datetime.date.today)),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_address', models.CharField(max_length=300)),
                ('stud_email', models.EmailField(max_length=30)),
                ('stud_adharno', models.CharField(max_length=12)),
                ('stud_religion', models.CharField(max_length=50)),
                ('stud_caste', models.CharField(max_length=50)),
                ('stud_nationality', models.CharField(max_length=30)),
                ('stud_dob', models.DateField()),
                ('stud_guardian', models.IntegerField()),
                ('stud_bloodgroup', models.IntegerField()),
                ('stud_gender', models.CharField(max_length=1)),
                ('mothertongue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user_settings.mothertongue')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.standard')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user_settings.state')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studmark_obtained', models.IntegerField()),
                ('exammark', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.exammark')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyear', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.academicyear')),
                ('classdivision', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.classdivision')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_permaddress', models.CharField(max_length=300)),
                ('parent_commaddress', models.CharField(max_length=300)),
                ('parent_contactno', models.CharField(max_length=13)),
                ('parent_email', models.CharField(max_length=30)),
                ('parent_adharno', models.CharField(max_length=12)),
                ('parent_occupation', models.CharField(max_length=300)),
                ('parent_bloodgroup', models.IntegerField()),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user_settings.relation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='student.student')),
            ],
        ),
    ]
