# Generated by Django 3.1.7 on 2021-02-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stud_caste',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_religion',
        ),
        migrations.AddField(
            model_name='student',
            name='caste',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='user_settings.caste'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='user_settings.religion'),
        ),
    ]
