# Generated by Django 3.1.7 on 2021-03-01 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='caste',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='user_settings.caste'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='user_settings.religion'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_bloodgroup',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'O+'), (6, 'O-'), (7, 'AB+'), (8, 'AB-')], default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_guardian',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
