# Generated by Django 3.1.7 on 2021-02-27 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('academic_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.parent')),
                ('academicyear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_settings.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='PTADesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pta_designation_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PTACommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_date', models.DateField(default=datetime.date.today)),
                ('comm_agenda', models.CharField(max_length=300)),
                ('comm_decision', models.CharField(max_length=2000)),
                ('committeeregistration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pta.committeeregistration')),
            ],
        ),
        migrations.CreateModel(
            name='PTAAttendedMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committeeregistration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pta.committeeregistration')),
                ('ptacommittee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pta.ptacommittee')),
            ],
        ),
        migrations.AddField(
            model_name='committeeregistration',
            name='ptadesignation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pta.ptadesignation'),
        ),
    ]
