# Generated by Django 3.1.7 on 2021-02-27 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_settings', '0001_initial'),
        ('student', '0001_initial'),
        ('pta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeregistration',
            name='Parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.parent'),
        ),
        migrations.AddField(
            model_name='committeeregistration',
            name='academicyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_settings.academicyear'),
        ),
        migrations.AddField(
            model_name='committeeregistration',
            name='ptadesignation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pta.ptadesignation'),
        ),
    ]
