# Generated by Django 3.1.7 on 2021-03-02 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0003_auto_20210302_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptacommittee',
            name='comm_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
