# Generated by Django 3.1.7 on 2021-02-27 07:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acyear_year', models.CharField(max_length=9)),
                ('acyear_startdate', models.DateField(default=django.utils.timezone.now)),
                ('acyear_enddate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_name', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExamDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('academicyear', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_per', models.IntegerField()),
                ('grade_grade', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exammark_max', models.IntegerField()),
                ('exammark_pass', models.IntegerField()),
                ('classsubject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.classsubject')),
                ('examdetail', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.examdetail')),
            ],
        ),
        migrations.AddField(
            model_name='classsubject',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.standard'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.subject'),
        ),
        migrations.CreateModel(
            name='ClassDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.division')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.standard')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCalander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accal_datefrom', models.DateField(default=django.utils.timezone.now)),
                ('accal_dateto', models.DateField(default=django.utils.timezone.now)),
                ('accal_particulars', models.CharField(max_length=1000)),
                ('academicyear', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academic_settings.academicyear')),
            ],
        ),
    ]
