# Generated by Django 3.1.7 on 2021-02-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0004_auto_20210226_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pettycash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pettycash_date', models.DateField()),
                ('pettycash_particulars', models.CharField(max_length=1000)),
                ('pettycash_amount', models.IntegerField(max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Pettycashapproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pettycashappr_date', models.DateField()),
                ('pettycashappr_voucherno', models.CharField(max_length=1000)),
                ('pettycashappr_voucherfile', models.CharField(max_length=20)),
                ('pettycash', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pettcash.pettycash')),
            ],
        ),
    ]
