# Generated by Django 3.1.7 on 2021-02-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=30)),
                ('profile_address', models.CharField(max_length=200)),
                ('profile_contactno', models.CharField(max_length=13)),
                ('profile_email', models.EmailField(max_length=30)),
            ],
        ),
    ]
