# Generated by Django 3.1.6 on 2021-02-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='profile_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='profile_contactno',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='profile_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='profile_name',
            field=models.CharField(max_length=30),
        ),
    ]
