# Generated by Django 3.1.6 on 2021-02-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_settings', '0002_auto_20210226_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='profile_email',
            field=models.EmailField(max_length=30),
        ),
    ]
