# Generated by Django 3.1.7 on 2021-02-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmanagementin',
            name='assetmgmtin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assetmanagementout',
            name='assetmgmtout_date',
            field=models.DateField(),
        ),
    ]
