# Generated by Django 3.1.7 on 2021-03-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmanagementdetails',
            name='assetdet_unit',
            field=models.CharField(default='', max_length=10),
        ),
    ]
