# Generated by Django 3.1.7 on 2021-03-02 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_assetmanagementdetails_assetdet_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmanagementin',
            name='assetmgmtin_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
